import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://www.toyota.com/dealers/")
    page.get_by_role("textbox", name="zip code").click()
    page.get_by_role("textbox", name="zip code").fill("60661")
    page.get_by_role("button", name="submit").click()
    page.get_by_role("button", name="Close Cookie Banner").click()
    page.locator(".gm-style > div > div:nth-child(2)").click()
    page.locator(".gm-style > div > div:nth-child(2)").click()
    page.locator(".gm-style > div > div:nth-child(2)").click()
    page.get_by_role("link", name="Toyota of Lincoln Park", exact=True).click()
    page.get_by_role("button", name="Request A Quote for Toyota of").click()
    page.get_by_role("combobox", name="Series name").click()
    page.get_by_role("option", name="BZ").click()
    page.get_by_role("combobox", name="Model name").click()
    page.get_by_role("option", name="XLE ELECTRIC MOTOR FRONT-WHEEL DRIVE", exact=True).click()
    page.get_by_role("textbox", name="First Name *").click()
    page.get_by_role("textbox", name="First Name *").fill("text")
    page.get_by_role("textbox", name="Last Name *").click()
    page.get_by_role("textbox", name="Last Name *").fill("s")
    page.get_by_role("textbox", name="First Name *").click()
    page.get_by_role("textbox", name="First Name *").click()
    page.get_by_role("textbox", name="First Name *").fill("sendto")
    page.get_by_role("textbox", name="First Name *").press("Tab")
    page.get_by_role("textbox", name="Last Name *").fill("text")
    page.get_by_role("textbox", name="Email *").click()
    page.get_by_role("textbox", name="Email *").fill("orville.antazo@icrossing.com")
    page.get_by_role("textbox", name="Phone").click()
    page.get_by_role("textbox", name="Phone").fill("(773) 818-1580")
    page.locator("#Request_A_Quote div").filter(has_text="Select a Dealer 60642 Your").nth(2).click()
    page.get_by_role("textbox", name="Address").click()
    page.get_by_role("textbox", name="Address").fill("770 W. Gladys")
    page.get_by_role("textbox", name="Address").press("Tab")
    page.get_by_role("textbox", name="City").fill("Chicago")
    page.get_by_text("+ Add Comments").click()
    page.get_by_label("Select a Vehicle * Required").get_by_text("+").click()
    page.get_by_text("+ Add Comments").click()
    page.get_by_text("+ Add Comments").click()
    page.get_by_text("+ Add Comments").click()
    page.get_by_role("button", name="Submit Request").click()
    page.locator(".modal-overlay").click()
